### ISSUE TITLE
Doesn't show content of file but return `JavaScript source, Unicode text, UTF-8 text`

### ISSUE THREAD

**Issue by ogios** [doronbehar/pistol#106]
![image](https://github.com/doronbehar/pistol/assets/96933655/136b6cdd-2541-41c5-a01e-0debefaf344e)

but there is content in that file, i don't know why it happens to some specific file

**Comment by doronbehar** [comment]
Could you attach please an example file, or a link to such a file?

**Comment by ogios** [comment]
@doronbehar ok, https://gist.github.com/ogios/0b11c7652b7d5013ed67d576e2b04f13#file-tailwind-config-ts

**Comment by doronbehar** [comment]
Yes so this is kind of by design like that. If you'd run `file --mime-type` on that file, you'd get:

```
javascript/application
```

Which doesn't has the `text/` prefix. I'm not sure this default behavior should change, but that is open for discussion. You can use this line in your `~/.config/pistol/pistol.conf`:

```
application/javascript bat --style=plain --paging=never --color=always %pistol-filename%
```

Where `bat` [this project](https://github.com/sharkdp/bat). The same goes for `application/json` files, as discussed in #34 .

Another improvement could be modifying the README to explain this behavior.

**Comment by ogios** [comment]
thanks, i understand it now.
and set cmd for specific type works

**Comment by doronbehar** [comment]
Hey @ogios after having a 2nd thought on the subject, and reading [this Q&A](https://stackoverflow.com/questions/21098865/text-javascript-vs-application-javascript) I decided to also make `pistol` read `application/javascript` files as if they were text files by default. You should be able to remove then the `application/javascript` line from your `pistol.conf` if you install the latest revision of `pistol`.
