### ISSUE TITLE
pistol not print JSON data

### ISSUE THREAD

**Issue by RonanMacF** [doronbehar/pistol#34]
What is the thinking behind not print JSON data and instead displaying a message stating that it is JSON data?

**Comment by doronbehar** [comment]
That's a good question :) The issue is the mime type of a JSON file is `application/json` and not `text/json` or anything that would match `text/*`. See this table:

https://github.com/doronbehar/pistol/blob/d827ec38668e60f9766f0407f7795af48ccf315d/internal_writers/map.go#L8-L20

Feel free @RonanMacF to try and a line there for `application/json` and use the `NewChromaWriter` as the key in that map.

**Comment by doronbehar** [comment]
Fixed in https://github.com/doronbehar/pistol/releases/tag/v0.1.6 .
